version: 2

jobs:
  test-node8:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

workflows:
  version: 2

  test:
    jobs:
      - test-node8
